name: Build bash

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Reason'     
        required: false
        default: 'Update package'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_arch:
          - arm
          - arm64
          - x86
          - x64
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Prerequisites
        run: |
          sudo apt install \
          ninja-build autogen \
          autoconf libtool \
          build-essential \
          cmake -y

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false
      - run: bash build.sh ${{ matrix.target_arch }}
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bash-${{ matrix.target_arch }}
          path: bash